### PR TITLE
Department module

### LINKED ISSUE #3: Departament Crud
# REQUIREMENTS
Only the administrator user will have access to this module.

The data required for this module are:
Nombre del Departamento

# DESIGN
Does not apply

# Acceptance Criteria
- [x] Created departaments
- [x] Show departaments
- [x] Updated departaments
- [x] Deleted departaments

### PR DESCRIPTION
**Pull request by FranckZnt19**
# Description
 - Creation department CRUD web
 - Creation department API only index for mobile deployment
 - Testing with rspec

 # Testing
run the following commands in your terminal:

1. bundle install
2. yarn install
3. rails db:create
4. rails db:migrate
5. rails db:test:prepare
6. bundle exec rspec

  ## Screenshots 
imagen

### CODE REVIEW

**Review by ArielMD — APPROVED** [review]
Nice job, there are files that you can remove (helpers and scaffolding styles), but everything is fine

**Review by EduardoGHdez — APPROVED** [review]
LGTM

**Comment by EduardoGHdez** [comment]
The PR was blocked due to low score in specs/Rubycritic

As an action item, we decided to ignore `Duplicative` code smells from the specs, bc this is normal in testing and we don't want to block PR's from being merge due to this error.

Merging from now, but it was filed a new issue to accomplish the action-item: https://github.com/BC-NOV-20-Proyectos/alerta-covid-web-team01/issues/21

**Review by MiguelOcegueraM — COMMENTED** [review]
Everything seems good! the code is very clean

**Pull request merged**
